services:
  consul:
    container_name: KunPengDJConsul
    image: consul:1.15.4
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0

  redis:
    container_name: KunPengDJRedis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  mysql:
    container_name: KunPengDJMySQL
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 243326
      # MYSQL_DATABASE: KunPengDJ_customer
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./volumes/mysql:/docker-entrypoint-initdb.d



