// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.0
// source: api/mymap/mymap.proto

package mymap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Mymap_GetDrivingInfo_FullMethodName = "/api.mymap.Mymap/GetDrivingInfo"
)

// MymapClient is the client API for Mymap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MymapClient interface {
	GetDrivingInfo(ctx context.Context, in *GetDrivingInfoReq, opts ...grpc.CallOption) (*GetDrivingInfoReply, error)
}

type mymapClient struct {
	cc grpc.ClientConnInterface
}

func NewMymapClient(cc grpc.ClientConnInterface) MymapClient {
	return &mymapClient{cc}
}

func (c *mymapClient) GetDrivingInfo(ctx context.Context, in *GetDrivingInfoReq, opts ...grpc.CallOption) (*GetDrivingInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDrivingInfoReply)
	err := c.cc.Invoke(ctx, Mymap_GetDrivingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MymapServer is the server API for Mymap service.
// All implementations must embed UnimplementedMymapServer
// for forward compatibility
type MymapServer interface {
	GetDrivingInfo(context.Context, *GetDrivingInfoReq) (*GetDrivingInfoReply, error)
	mustEmbedUnimplementedMymapServer()
}

// UnimplementedMymapServer must be embedded to have forward compatible implementations.
type UnimplementedMymapServer struct {
}

func (UnimplementedMymapServer) GetDrivingInfo(context.Context, *GetDrivingInfoReq) (*GetDrivingInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrivingInfo not implemented")
}
func (UnimplementedMymapServer) mustEmbedUnimplementedMymapServer() {}

// UnsafeMymapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MymapServer will
// result in compilation errors.
type UnsafeMymapServer interface {
	mustEmbedUnimplementedMymapServer()
}

func RegisterMymapServer(s grpc.ServiceRegistrar, srv MymapServer) {
	s.RegisterService(&Mymap_ServiceDesc, srv)
}

func _Mymap_GetDrivingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrivingInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MymapServer).GetDrivingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mymap_GetDrivingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MymapServer).GetDrivingInfo(ctx, req.(*GetDrivingInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Mymap_ServiceDesc is the grpc.ServiceDesc for Mymap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mymap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.mymap.Mymap",
	HandlerType: (*MymapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDrivingInfo",
			Handler:    _Mymap_GetDrivingInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mymap/mymap.proto",
}
